### ISSUE TITLE
Add a way to filter GGG messages from the Help and Information forum

### ISSUE THREAD

**Issue by DanNeely** [ccbrown/gggtracker#139] opened 2024-12-25 04:01 UTC
Since POE 2 launched there has been a huge torrent of support messages triggering staff replies that overwhelms the occasional message of broader interest.  99% of the user requests are for the same handful of issues, and really aren't of broader interest.

This normally happens briefly on POE2 league launch but quickly dissipates.  For POE2 it's showing no sign of stopping; and since one of the common ones is lack of response to their support email - which is currently taking 10+ days to get a response - is unlikely to be fixed anytime soon.

I'd prefer a user toggleable way to switch between views that include or don't include that forum instead of just excluding it entirely is because when it's not being clogged with repetitive issues it is more likely to have interesting GGG messages.

**Comment by ccbrown** [comment] 2024-12-26 00:28
This is definitely something I'm keen to do, but I'm closing this issue as a duplicate of https://github.com/ccbrown/gggtracker/issues/138.

**Closed by ccbrown** 2024-12-26 00:28 UTC
Labels: duplicate, enhancement
